kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: webservers
  name: spezzys-rwx-role
rules:
- apiGroups: ["", "batch", "extensions", "apps", "cert-manager.io", "networking.k8s.io", "service"]
  resources: ["*"]
  verbs: ["*"]