---
masters:
  hosts:
    challenger-master:
      ansible_host: 10.99.0.10
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/challenger-master_rsa
  vars: 
    kube-vip-ip: 10.99.0.21
    kube-vip-interface: ens33
    kube-vip-version: v1.0.4

workers:
  hosts: 
    challenger-worker-1:
      ansible_host: 10.99.0.11
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/challenger-master_rsa
    challenger-worker-2: 
      ansible_host: 10.99.0.12
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/challenger-master_rsa