- hosts: 'workers, masters'
  become: yes
  become_user: cspears
  tasks:
    - name: Create new user named 'kube'
      user: name=kube append=yes state=present createhome=yes shell=/bin/bash

    - name: Allow 'kube' to run sudo without requiring a password
      lineinfile:
        dest: /etc/sudoers
        line: 'kube ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Add authorized key from 'autoAnsible' for 'kube'
      authorized_key: user=kube key="{{item}}"
      with_file:
        - ~/.ssh/challenger-master_rsa.pub