---
masters:
  hosts:
    challenger-master:
      ansible_host: 10.99.0.10
      ansible_user: ansible

workers:
  hosts: 
    challenger-worker-1:
      ansible_host: 10.99.0.11
      ansible_user: ansible
    challenger-worker-2: 
      ansible_host: 10.99.0.12
      ansible_user: ansible